name: PHP Codeception Tests - develop

on: push

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests-develop.yml@main
    with:
      module-id: calendar
      use-rest-module: true
      install-composer: true